version: "3.9"

services:
  eurekaserver:
    image: eurekaserver:latest
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eurekaserver
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - SERVER_PORT=8761
    networks:
      - springbootmicroservicesnetwork

  commonservice:
    image: commonservice:latest
    build:
      context: ./commonservice
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      - SPRING_APPLICATION_NAME=commonservice
      - SPRING_CLOUD_NETFLIX_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SERVER_PORT=1111
    depends_on:
      - eurekaserver
    networks:
      - springbootmicroservicesnetwork


networks:
  springbootmicroservicesnetwork:
    driver: bridge