name: CI/CD Pipeline for Auth Servive

on:
  workflow_run:
    workflows: ["CI/CD Pipeline for Eureka Server"]
    branches: [ "main" ]
    types:
      - completed

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -f authservice/pom.xml clean install -DskipTests

      - name: Run Tests
        run: mvn -B -f authservice/pom.xml test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -f authservice/pom.xml clean package

      - name: Dockerize & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: noyandocker/springbootmicroserviceswithsecurityauthservice
          tags: latest
          registry: docker.io
          dockerfile: authservice/Dockerfile
          directory: authservice
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
